// filepath: src/lib/constants/ofertas.ts
import type { PremiumPromo, OfertaConfig } from "@/types/ofertas";

export const DEFAULT_PREMIUM_PROMOS: PremiumPromo[] = [
  {
    id: "promo-jugos-clight-tang",
    titulo: "Jugos Clight / Tang en Oferta (1 caja x $150 / 3 cajas x $300)",
    precio: 150,
    cantidad: 1,
    imagen: "/promos/jugos-clight-tang.jpg",
    activa: true,
    sucursalId: null,
    escalaPrecios: [
      { minCantidad: 3, precioUnitario: 100, etiqueta: "3 cajas x $300 ($100 c/u)" }
    ],
  },
  {
    id: "promo-pack-licores-finde",
    titulo: "Pack Finde: Gin Brighton + Fernet Buhero Negro + Whisky Royal Stag",
    precio: 1200,
    cantidad: 1,
    imagen: "/promos/pack-licores-finde.jpg",
    activa: true,
    sucursalId: null,
  },
  {
    id: "promo-jamon-dona-coca",
    titulo: "Jamón Extra Doña Coca x KG",
    precio: 560,
    cantidad: 1,
    imagen: "/promos/jamon-dona-coca.jpg",
    activa: true,
    sucursalId: null,
  },
  {
    id: "promo-panceta-camposur",
    titulo: "Panceta Americana CampoSUR en Fetas (x 100g)",
    precio: 35,
    cantidad: 1,
    imagen: "/promos/panceta-camposur.jpg",
    activa: true,
    sucursalId: null,
  },
];

export const DEFAULT_CAROUSEL_SLIDES: import("@/types/ofertas").CarouselSlide[] = [
  {
    id: "promo-jugos-clight-tang",
    titulo: "",
    subtitulo: "",
    imagenDesktop: "/promos/jugos-clight-tang.jpg",
    imagenMobile: "/promos/jugos-clight-tang.jpg",
    ctaTexto: "",
    ctaLink: "/catalogo?search=clight+tang",
    colorAccent: "#E8302A",
    activo: true,
    orden: 1,
  },
  {
    id: "promo-pack-licores-finde",
    titulo: "",
    subtitulo: "",
    imagenDesktop: "/promos/pack-licores-finde.jpg",
    imagenMobile: "/promos/pack-licores-finde.jpg",
    ctaTexto: "",
    ctaLink: "/catalogo?categoria=BEBIDAS+ALCOH%C3%93LICAS",
    colorAccent: "#E8302A",
    activo: true,
    orden: 2,
  },
  {
    id: "promo-jamon-dona-coca",
    titulo: "",
    subtitulo: "",
    imagenDesktop: "/promos/jamon-dona-coca.jpg",
    imagenMobile: "/promos/jamon-dona-coca.jpg",
    ctaTexto: "",
    ctaLink: "/catalogo?categoria=CARNES+Y+EMBUTIDOS",
    colorAccent: "#E8302A",
    activo: true,
    orden: 3,
  },
  {
    id: "promo-panceta-camposur",
    titulo: "",
    subtitulo: "",
    imagenDesktop: "/promos/panceta-camposur.jpg",
    imagenMobile: "/promos/panceta-camposur.jpg",
    ctaTexto: "",
    ctaLink: "/catalogo?categoria=CARNES+Y+EMBUTIDOS",
    colorAccent: "#E8302A",
    activo: true,
    orden: 4,
  },
];

export const DEFAULT_OFERTAS_CONFIG: OfertaConfig = {
  activa: true,
  titulo: "Ofertas Destacadas de la Semana",
  subtitulo: "Aprovechá precios únicos y combos especiales por tiempo limitado",
  productos: [
    {
      codigo: "5797",
      nombre: "PAPAS CONG. MC CAIN CORTE FINO 2.5KG",
      precioOriginal: 325,
      precioOferta: 250,
      descuento: 23,
      imagen: "/ofertas/papas-mccain.jpg",
      categoria: "Congelados",
      destacado: true,
      escalaPrecios: [
        { minCantidad: 8, precioUnitario: 236, etiqueta: "Caja x 8 u. ($236 c/u)" }
      ],
    },
    {
      codigo: "7730430004349",
      nombre: "FIDEOS GRANNY 400G (PROMO 3X$99)",
      precioOriginal: 120,
      precioOferta: 99,
      descuento: 18,
      imagen: "/ofertas/fideos-granny.jpg",
      categoria: "Harinas, Pastas y Legumbres",
      destacado: true,
    },
    {
      codigo: "MM7730493084159",
      nombre: "VINO EL TAIPERO 1L (PROMO 2X$180)",
      precioOriginal: 198,
      precioOferta: 180,
      descuento: 10,
      imagen: "/ofertas/vino-el-taipero.jpg",
      categoria: "Bebidas",
      destacado: true,
    },
    {
      codigo: "DULCE-COLONIAL-500",
      nombre: "DULCE DE LECHE COLONIAL 500G",
      precioOriginal: 75,
      precioOferta: 50,
      descuento: 33,
      imagen: "/ofertas/dulce-de-leche-colonial.jpg",
      categoria: "Dulces y Mermeladas",
      destacado: true,
    },
    {
      codigo: "9768",
      nombre: "MORTADELA ARIZONA EN FETAS (100G)",
      precioOriginal: 22,
      precioOferta: 17,
      descuento: 23,
      imagen: "/ofertas/mortadela-arizona.jpg",
      categoria: "Fiambres y Carnes",
      destacado: true,
    },
    {
      codigo: "COMBO-COLOLO-ATUN",
      nombre: "COMBO MAYONESA COLOLO 200G + ATÚN FRESCO MAR",
      precioOriginal: 125,
      precioOferta: 90,
      descuento: 28,
      imagen: "/ofertas/combo-mayonesa-atun.jpg",
      categoria: "Salsas y Aderezos",
      destacado: true,
    },
  ],
  mainCarousel: DEFAULT_CAROUSEL_SLIDES,
  premiumPromos: DEFAULT_PREMIUM_PROMOS,
  brandBanners: [],
  sponsoredProducts: [],
  categoryOffers: [],
  flashOffers: [],
  updatedAt: new Date().toISOString(),
};
