// filepath: src/lib/constants/ofertas.ts
import type { PremiumPromo, OfertaConfig } from "@/types/ofertas";

export const DEFAULT_PREMIUM_PROMOS: PremiumPromo[] = [
  {
    id: "papas-mccain-2500g",
    titulo: "Papas Mc Cain Corte Fino 2.5kg",
    precio: 250,
    cantidad: 1,
    imagen: "/ofertas/papas-mccain.jpg",
    activa: true,
    sucursalId: null,
    escalaPrecios: [
      { minCantidad: 8, precioUnitario: 236, etiqueta: "Caja x 8 u. ($236 c/u)" }
    ],
  },
  {
    id: "fideos-granny-3x99",
    titulo: "Fideos Granny 400g (Promo 3 x $99)",
    precio: 99,
    cantidad: 3,
    imagen: "/ofertas/fideos-granny.jpg",
    activa: true,
    sucursalId: null,
  },
  {
    id: "vino-el-taipero-2x180",
    titulo: "Vino El Taipero Bodega Rosés 1L (2 x $180)",
    precio: 180,
    cantidad: 2,
    imagen: "/ofertas/vino-el-taipero.jpg",
    activa: true,
    sucursalId: null,
  },
  {
    id: "dulce-de-leche-colonial-500g",
    titulo: "Dulce de Leche Colonial 500g",
    precio: 50,
    cantidad: 1,
    imagen: "/ofertas/dulce-de-leche-colonial.jpg",
    activa: true,
    sucursalId: null,
  },
  {
    id: "mortadela-arizona-100g",
    titulo: "Mortadela Arizona en Fetas ($17 x 100g)",
    precio: 17,
    cantidad: 1,
    imagen: "/ofertas/mortadela-arizona.jpg",
    activa: true,
    sucursalId: null,
  },
  {
    id: "combo-mayonesa-cololo-atun",
    titulo: "Combo Mayonesa Cololo 200g + Atún Fresco Mar",
    precio: 90,
    cantidad: 1,
    imagen: "/ofertas/combo-mayonesa-atun.jpg",
    activa: true,
    sucursalId: null,
  },
];

export const DEFAULT_OFERTAS_CONFIG: OfertaConfig = {
  activa: true,
  titulo: "Ofertas Destacadas de la Semana",
  subtitulo: "Aprovechá precios únicos y combos especiales por tiempo limitado",
  productos: [
    {
      codigo: "5797",
      nombre: "PAPAS CONG. MC CAIN CORTE FINO 2.5KG",
      precioOriginal: 325,
      precioOferta: 250,
      descuento: 23,
      imagen: "/ofertas/papas-mccain.jpg",
      categoria: "Congelados",
      destacado: true,
      escalaPrecios: [
        { minCantidad: 8, precioUnitario: 236, etiqueta: "Caja x 8 u. ($236 c/u)" }
      ],
    },
    {
      codigo: "7730430004349",
      nombre: "FIDEOS GRANNY 400G (PROMO 3X$99)",
      precioOriginal: 120,
      precioOferta: 99,
      descuento: 18,
      imagen: "/ofertas/fideos-granny.jpg",
      categoria: "Harinas, Pastas y Legumbres",
      destacado: true,
    },
    {
      codigo: "MM7730493084159",
      nombre: "VINO EL TAIPERO 1L (PROMO 2X$180)",
      precioOriginal: 198,
      precioOferta: 180,
      descuento: 10,
      imagen: "/ofertas/vino-el-taipero.jpg",
      categoria: "Bebidas",
      destacado: true,
    },
    {
      codigo: "DULCE-COLONIAL-500",
      nombre: "DULCE DE LECHE COLONIAL 500G",
      precioOriginal: 75,
      precioOferta: 50,
      descuento: 33,
      imagen: "/ofertas/dulce-de-leche-colonial.jpg",
      categoria: "Dulces y Mermeladas",
      destacado: true,
    },
    {
      codigo: "9768",
      nombre: "MORTADELA ARIZONA EN FETAS (100G)",
      precioOriginal: 22,
      precioOferta: 17,
      descuento: 23,
      imagen: "/ofertas/mortadela-arizona.jpg",
      categoria: "Fiambres y Carnes",
      destacado: true,
    },
    {
      codigo: "COMBO-COLOLO-ATUN",
      nombre: "COMBO MAYONESA COLOLO 200G + ATÚN FRESCO MAR",
      precioOriginal: 125,
      precioOferta: 90,
      descuento: 28,
      imagen: "/ofertas/combo-mayonesa-atun.jpg",
      categoria: "Salsas y Aderezos",
      destacado: true,
    },
  ],
  premiumPromos: DEFAULT_PREMIUM_PROMOS,
  brandBanners: [],
  sponsoredProducts: [],
  categoryOffers: [],
  flashOffers: [],
  updatedAt: new Date().toISOString(),
};
